// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';

export function AddPlaylist(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function GetPlaylists():Promise<Array<playlist.Playlist>>;

export function UpdatePlaylistName(arg1:number,arg2:string):Promise<void>;

export function UpdatePlaylistThumbnail(arg1:number,arg2:string):Promise<void>;
