// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaylist(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['playlist']['PlaylistDB']['AddPlaylist'](arg1, arg2, arg3, arg4, arg5);
}

export function DeletePlaylist(arg1) {
  return window['go']['playlist']['PlaylistDB']['DeletePlaylist'](arg1);
}

export function GetPlaylists() {
  return window['go']['playlist']['PlaylistDB']['GetPlaylists']();
}

export function UpdatePlaylistName(arg1, arg2) {
  return window['go']['playlist']['PlaylistDB']['UpdatePlaylistName'](arg1, arg2);
}

export function UpdatePlaylistThumbnail(arg1, arg2) {
  return window['go']['playlist']['PlaylistDB']['UpdatePlaylistThumbnail'](arg1, arg2);
}
