// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllRegisteredFiles() {
  return window['go']['main']['App']['ClearAllRegisteredFiles']();
}

export function CloseApplication() {
  return window['go']['main']['App']['CloseApplication']();
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function DirectDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['DirectDownload'](arg1, arg2, arg3);
}

export function GetActivePlaylists() {
  return window['go']['main']['App']['GetActivePlaylists']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetConfigString(arg1) {
  return window['go']['main']['App']['GetConfigString'](arg1);
}

export function GetConfirmCloseEnabled() {
  return window['go']['main']['App']['GetConfirmCloseEnabled']();
}

export function GetDaemonLogLines(arg1) {
  return window['go']['main']['App']['GetDaemonLogLines'](arg1);
}

export function GetDaemonLogLinesWithLevel(arg1, arg2) {
  return window['go']['main']['App']['GetDaemonLogLinesWithLevel'](arg1, arg2);
}

export function GetDownloadHistoryPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDownloadHistoryPage'](arg1, arg2, arg3, arg4);
}

export function GetLegalDisclaimerAccepted() {
  return window['go']['main']['App']['GetLegalDisclaimerAccepted']();
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetRegisteredFiles(arg1, arg2) {
  return window['go']['main']['App']['GetRegisteredFiles'](arg1, arg2);
}

export function GetSettingString(arg1) {
  return window['go']['main']['App']['GetSettingString'](arg1);
}

export function GetUILogLines(arg1) {
  return window['go']['main']['App']['GetUILogLines'](arg1);
}

export function GetUILogLinesWithLevel(arg1, arg2) {
  return window['go']['main']['App']['GetUILogLinesWithLevel'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HandleFatalError(arg1) {
  return window['go']['main']['App']['HandleFatalError'](arg1);
}

export function IsDaemonRunning() {
  return window['go']['main']['App']['IsDaemonRunning']();
}

export function IsStartupComplete() {
  return window['go']['main']['App']['IsStartupComplete']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function RegisterAllFailedForRetryManual() {
  return window['go']['main']['App']['RegisterAllFailedForRetryManual']();
}

export function RegisterDirectory(arg1) {
  return window['go']['main']['App']['RegisterDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetConfigString(arg1, arg2) {
  return window['go']['main']['App']['SetConfigString'](arg1, arg2);
}

export function SetConfirmCloseEnabled(arg1) {
  return window['go']['main']['App']['SetConfirmCloseEnabled'](arg1);
}

export function SetLegalDisclaimerAccepted(arg1) {
  return window['go']['main']['App']['SetLegalDisclaimerAccepted'](arg1);
}

export function SetManualRetry(arg1) {
  return window['go']['main']['App']['SetManualRetry'](arg1);
}

export function SetSettingPreparsed(arg1, arg2) {
  return window['go']['main']['App']['SetSettingPreparsed'](arg1, arg2);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}

export function UpdatePlaylistDirectory(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlaylistDirectory'](arg1, arg2);
}

export function ValidateAndAddPlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateAndAddPlaylist'](arg1, arg2, arg3);
}
