// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';

export function GetPlaylists():Promise<Array<playlist.Playlist>>;

export function HandleFatalError(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;
