// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';

export function DeletePlaylist(arg1:number):Promise<void>;

export function GetClipboard():Promise<string>;

export function GetPlaylists():Promise<Array<playlist.Playlist>>;

export function HandleFatalError(arg1:string):Promise<void>;

export function IsStartupComplete():Promise<boolean>;

export function OpenDirectory(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function UpdatePlaylistDirectory(arg1:number,arg2:string):Promise<void>;

export function ValidateAndAddPlaylist(arg1:string,arg2:string,arg3:string):Promise<void>;
