// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function HandleFatalError(arg1) {
  return window['go']['main']['App']['HandleFatalError'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdatePlaylistDirectory(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlaylistDirectory'](arg1, arg2);
}

export function ValidateAndAddPlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateAndAddPlaylist'](arg1, arg2, arg3);
}
