// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';
import {download} from '../models';

export function CloseApplication():Promise<void>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function DirectDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetActivePlaylists():Promise<Array<playlist.Playlist>>;

export function GetClipboard():Promise<string>;

export function GetConfirmCloseEnabled():Promise<boolean>;

export function GetDaemonLogLines(arg1:number):Promise<Array<string>>;

export function GetDaemonLogLinesWithLevel(arg1:number,arg2:string):Promise<Array<string>>;

export function GetDownloadHistoryPage(arg1:number,arg2:number,arg3:boolean,arg4:boolean):Promise<Array<download.Download>>;

export function GetLegalDisclaimerAccepted():Promise<boolean>;

export function GetRecentLogs():Promise<Array<any>>;

export function GetSettingString(arg1:string):Promise<string>;

export function GetUILogLines(arg1:number):Promise<Array<string>>;

export function GetUILogLinesWithLevel(arg1:number,arg2:string):Promise<Array<string>>;

export function HandleFatalError(arg1:string):Promise<void>;

export function IsDaemonRunning():Promise<boolean>;

export function IsStartupComplete():Promise<boolean>;

export function OpenDirectory(arg1:string):Promise<void>;

export function RegisterAllFailedForRetryManual():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetConfirmCloseEnabled(arg1:boolean):Promise<void>;

export function SetLegalDisclaimerAccepted(arg1:boolean):Promise<void>;

export function SetManualRetry(arg1:number):Promise<void>;

export function SetSettingPreparsed(arg1:string,arg2:string):Promise<void>;

export function StartDaemon():Promise<void>;

export function StopDaemon():Promise<void>;

export function UpdatePlaylistDirectory(arg1:number,arg2:string):Promise<void>;

export function ValidateAndAddPlaylist(arg1:string,arg2:string,arg3:string):Promise<void>;
